CREATE TABLE FUNCIONARIO (
ID_FUNC int AUTO_INCREMENT (100,1) PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
CARGO VARCHAR (30),
);

CREATE TABLE ESTOQUE (
ID_LOTE int PRIMARY KEY,
NOME_PRODUTO VARCHAR(80),
QUANTIDADE_LOTE INT,
VALOR_UNITARIO DECIMAL,
FOREIGN KEY (ID_FUNC) REFERENCES FUNCIONARIO (ID_FUNC)
);